const std = @import("std");

/// Build LibWapcaplet + LibParserUtils + LibCSS as a single static library.
pub fn buildLibCss(b: *std.Build, target: std.Build.ResolvedTarget, optimize: std.builtin.OptimizeMode) *std.Build.Step.Compile {
    const common_cflags = &[_][]const u8{
        "-D_BSD_SOURCE",
        "-D_DEFAULT_SOURCE",
        "-std=c99",
        "-fno-sanitize=undefined",
    };

    // --- LibWapcaplet ---
    const libwapcaplet = b.addLibrary(.{
        .name = "wapcaplet",
        .linkage = .static,
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    libwapcaplet.addCSourceFiles(.{
        .root = b.path("deps/libwapcaplet"),
        .files = &.{
            "src/libwapcaplet.c",
        },
        .flags = common_cflags,
    });
    libwapcaplet.addIncludePath(b.path("deps/libwapcaplet/include"));

    // --- LibParserUtils ---
    const libparserutils = b.addLibrary(.{
        .name = "parserutils",
        .linkage = .static,
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    libparserutils.addCSourceFiles(.{
        .root = b.path("deps/libparserutils"),
        .files = &.{
            "src/charset/aliases.c",
            "src/charset/codec.c",
            "src/charset/codecs/codec_8859.c",
            "src/charset/codecs/codec_ascii.c",
            "src/charset/codecs/codec_ext8.c",
            "src/charset/codecs/codec_utf16.c",
            "src/charset/codecs/codec_utf8.c",
            "src/charset/encodings/utf16.c",
            "src/charset/encodings/utf8.c",
            "src/input/filter.c",
            "src/input/inputstream.c",
            "src/utils/buffer.c",
            "src/utils/errors.c",
            "src/utils/stack.c",
            "src/utils/vector.c",
        },
        .flags = common_cflags,
    });
    libparserutils.addIncludePath(b.path("deps/libparserutils/include"));
    libparserutils.addIncludePath(b.path("deps/libparserutils/src"));

    // --- LibCSS ---
    const libcss = b.addLibrary(.{
        .name = "css",
        .linkage = .static,
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    const libcss_cflags = &[_][]const u8{
        "-D_BSD_SOURCE",
        "-D_DEFAULT_SOURCE",
        "-D_ALIGNED=",
        "-std=c99",
        "-fno-sanitize=undefined",
    };
    libcss.addCSourceFiles(.{
        .root = b.path("deps/libcss"),
        .files = &libcss_sources,
        .flags = libcss_cflags,
    });
    // LibCSS include paths
    libcss.addIncludePath(b.path("deps/libcss/include"));
    libcss.addIncludePath(b.path("deps/libcss/src"));
    // Dependencies' include paths
    libcss.addIncludePath(b.path("deps/libparserutils/include"));
    libcss.addIncludePath(b.path("deps/libwapcaplet/include"));

    // Include wapcaplet and parserutils sources directly in libcss
    // to avoid separate linking that forces object resolution
    libcss.addCSourceFiles(.{
        .root = b.path("deps/libwapcaplet"),
        .files = &.{"src/libwapcaplet.c"},
        .flags = common_cflags,
    });
    libcss.addCSourceFiles(.{
        .root = b.path("deps/libparserutils"),
        .files = &.{
            "src/charset/aliases.c",
            "src/charset/codec.c",
            "src/charset/codecs/codec_8859.c",
            "src/charset/codecs/codec_ascii.c",
            "src/charset/codecs/codec_ext8.c",
            "src/charset/codecs/codec_utf16.c",
            "src/charset/codecs/codec_utf8.c",
            "src/charset/encodings/utf16.c",
            "src/charset/encodings/utf8.c",
            "src/input/filter.c",
            "src/input/inputstream.c",
            "src/utils/buffer.c",
            "src/utils/errors.c",
            "src/utils/stack.c",
            "src/utils/vector.c",
        },
        .flags = common_cflags,
    });
    libcss.addIncludePath(b.path("deps/libparserutils/src"));
    libcss.addIncludePath(b.path("deps/libparserutils/src/charset"));

    return libcss;
}

const libcss_sources = [_][]const u8{
    "src/charset/detect.c",
    "src/lex/lex.c",
    "src/parse/font_face.c",
    "src/parse/important.c",
    "src/parse/language.c",
    "src/parse/mq.c",
    "src/parse/parse.c",
    "src/parse/properties/azimuth.c",
    "src/parse/properties/background.c",
    "src/parse/properties/background_position.c",
    "src/parse/properties/border.c",
    "src/parse/properties/border_color.c",
    "src/parse/properties/border_spacing.c",
    "src/parse/properties/border_style.c",
    "src/parse/properties/border_width.c",
    "src/parse/properties/clip.c",
    "src/parse/properties/column_rule.c",
    "src/parse/properties/columns.c",
    "src/parse/properties/content.c",
    // Note: css_property_parser_gen.c is a code generator, not a library source
    "src/parse/properties/cue.c",
    "src/parse/properties/cursor.c",
    "src/parse/properties/elevation.c",
    "src/parse/properties/fill_opacity.c",
    "src/parse/properties/flex.c",
    "src/parse/properties/flex_flow.c",
    "src/parse/properties/font.c",
    "src/parse/properties/font_family.c",
    "src/parse/properties/font_weight.c",
    "src/parse/properties/list_style.c",
    "src/parse/properties/list_style_type.c",
    "src/parse/properties/margin.c",
    "src/parse/properties/opacity.c",
    "src/parse/properties/outline.c",
    "src/parse/properties/overflow.c",
    "src/parse/properties/padding.c",
    "src/parse/properties/pause.c",
    "src/parse/properties/play_during.c",
    "src/parse/properties/properties.c",
    "src/parse/properties/quotes.c",
    "src/parse/properties/stroke_opacity.c",
    "src/parse/properties/text_decoration.c",
    "src/parse/properties/utils.c",
    "src/parse/properties/voice_family.c",
    // Auto-generated property parsers (from css_property_parser_gen + sed fix)
    "src/parse/properties/generated/align_content.c", "src/parse/properties/generated/align_items.c", "src/parse/properties/generated/align_self.c", "src/parse/properties/generated/background_attachment.c", "src/parse/properties/generated/background_color.c", "src/parse/properties/generated/background_image.c", "src/parse/properties/generated/background_repeat.c", "src/parse/properties/generated/border_bottom.c", "src/parse/properties/generated/border_bottom_color.c", "src/parse/properties/generated/border_bottom_style.c", "src/parse/properties/generated/border_bottom_width.c", "src/parse/properties/generated/border_collapse.c", "src/parse/properties/generated/border_side_color.c", "src/parse/properties/generated/border_side_style.c", "src/parse/properties/generated/border_side_width.c", "src/parse/properties/generated/border_left.c", "src/parse/properties/generated/border_left_color.c", "src/parse/properties/generated/border_left_style.c", "src/parse/properties/generated/border_left_width.c", "src/parse/properties/generated/border_right.c", "src/parse/properties/generated/border_right_color.c", "src/parse/properties/generated/border_right_style.c", "src/parse/properties/generated/border_right_width.c", "src/parse/properties/generated/border_top.c", "src/parse/properties/generated/border_top_color.c", "src/parse/properties/generated/border_top_style.c", "src/parse/properties/generated/border_top_width.c", "src/parse/properties/generated/bottom.c", "src/parse/properties/generated/box_sizing.c", "src/parse/properties/generated/break_after.c", "src/parse/properties/generated/break_before.c", "src/parse/properties/generated/break_inside.c", "src/parse/properties/generated/caption_side.c", "src/parse/properties/generated/clear.c", "src/parse/properties/generated/color.c", "src/parse/properties/generated/column_count.c", "src/parse/properties/generated/column_fill.c", "src/parse/properties/generated/column_gap.c", "src/parse/properties/generated/column_rule_color.c", "src/parse/properties/generated/column_rule_style.c", "src/parse/properties/generated/column_rule_width.c", "src/parse/properties/generated/column_span.c", "src/parse/properties/generated/column_width.c", "src/parse/properties/generated/counter_increment.c", "src/parse/properties/generated/counter_reset.c", "src/parse/properties/generated/cue_after.c", "src/parse/properties/generated/cue_before.c", "src/parse/properties/generated/direction.c", "src/parse/properties/generated/display.c", "src/parse/properties/generated/empty_cells.c", "src/parse/properties/generated/flex_basis.c", "src/parse/properties/generated/flex_direction.c", "src/parse/properties/generated/flex_grow.c", "src/parse/properties/generated/flex_shrink.c", "src/parse/properties/generated/flex_wrap.c", "src/parse/properties/generated/float.c", "src/parse/properties/generated/font_size.c", "src/parse/properties/generated/font_style.c", "src/parse/properties/generated/font_variant.c", "src/parse/properties/generated/height.c", "src/parse/properties/generated/justify_content.c", "src/parse/properties/generated/left.c", "src/parse/properties/generated/letter_spacing.c", "src/parse/properties/generated/line_height.c", "src/parse/properties/generated/list_style_image.c", "src/parse/properties/generated/list_style_position.c", "src/parse/properties/generated/margin_bottom.c", "src/parse/properties/generated/margin_side.c", "src/parse/properties/generated/margin_left.c", "src/parse/properties/generated/margin_right.c", "src/parse/properties/generated/margin_top.c", "src/parse/properties/generated/max_height.c", "src/parse/properties/generated/max_width.c", "src/parse/properties/generated/min_height.c", "src/parse/properties/generated/min_width.c", "src/parse/properties/generated/order.c", "src/parse/properties/generated/orphans.c", "src/parse/properties/generated/outline_color.c", "src/parse/properties/generated/outline_style.c", "src/parse/properties/generated/outline_width.c", "src/parse/properties/generated/overflow_x.c", "src/parse/properties/generated/overflow_y.c", "src/parse/properties/generated/padding_bottom.c", "src/parse/properties/generated/padding_side.c", "src/parse/properties/generated/padding_left.c", "src/parse/properties/generated/padding_right.c", "src/parse/properties/generated/padding_top.c", "src/parse/properties/generated/page_break_after.c", "src/parse/properties/generated/page_break_before.c", "src/parse/properties/generated/page_break_inside.c", "src/parse/properties/generated/pause_after.c", "src/parse/properties/generated/pause_before.c", "src/parse/properties/generated/pitch.c", "src/parse/properties/generated/pitch_range.c", "src/parse/properties/generated/position.c", "src/parse/properties/generated/richness.c", "src/parse/properties/generated/right.c", "src/parse/properties/generated/side.c", "src/parse/properties/generated/speak.c", "src/parse/properties/generated/speak_header.c", "src/parse/properties/generated/speak_numeral.c", "src/parse/properties/generated/speak_punctuation.c", "src/parse/properties/generated/speech_rate.c", "src/parse/properties/generated/stress.c", "src/parse/properties/generated/table_layout.c", "src/parse/properties/generated/text_align.c", "src/parse/properties/generated/text_indent.c", "src/parse/properties/generated/text_transform.c", "src/parse/properties/generated/top.c", "src/parse/properties/generated/unicode_bidi.c", "src/parse/properties/generated/vertical_align.c", "src/parse/properties/generated/visibility.c", "src/parse/properties/generated/volume.c", "src/parse/properties/generated/white_space.c", "src/parse/properties/generated/widows.c", "src/parse/properties/generated/width.c", "src/parse/properties/generated/word_spacing.c", "src/parse/properties/generated/writing_mode.c", "src/parse/properties/generated/z_index.c",
    "src/parse/propstrings.c",
    "src/select/arena.c",
    "src/select/calc.c",
    "src/select/computed.c",
    "src/select/dispatch.c",
    "src/select/font_face.c",
    "src/select/format_list_style.c",
    "src/select/hash.c",
    "src/select/properties/align_content.c",
    "src/select/properties/align_items.c",
    "src/select/properties/align_self.c",
    "src/select/properties/azimuth.c",
    "src/select/properties/background_attachment.c",
    "src/select/properties/background_color.c",
    "src/select/properties/background_image.c",
    "src/select/properties/background_position.c",
    "src/select/properties/background_repeat.c",
    "src/select/properties/border_bottom_color.c",
    "src/select/properties/border_bottom_style.c",
    "src/select/properties/border_bottom_width.c",
    "src/select/properties/border_collapse.c",
    "src/select/properties/border_left_color.c",
    "src/select/properties/border_left_style.c",
    "src/select/properties/border_left_width.c",
    "src/select/properties/border_right_color.c",
    "src/select/properties/border_right_style.c",
    "src/select/properties/border_right_width.c",
    "src/select/properties/border_spacing.c",
    "src/select/properties/border_top_color.c",
    "src/select/properties/border_top_style.c",
    "src/select/properties/border_top_width.c",
    "src/select/properties/bottom.c",
    "src/select/properties/box_sizing.c",
    "src/select/properties/break_after.c",
    "src/select/properties/break_before.c",
    "src/select/properties/break_inside.c",
    "src/select/properties/caption_side.c",
    "src/select/properties/clear.c",
    "src/select/properties/clip.c",
    "src/select/properties/color.c",
    "src/select/properties/column_count.c",
    "src/select/properties/column_fill.c",
    "src/select/properties/column_gap.c",
    "src/select/properties/column_rule_color.c",
    "src/select/properties/column_rule_style.c",
    "src/select/properties/column_rule_width.c",
    "src/select/properties/column_span.c",
    "src/select/properties/column_width.c",
    "src/select/properties/content.c",
    "src/select/properties/counter_increment.c",
    "src/select/properties/counter_reset.c",
    "src/select/properties/cue_after.c",
    "src/select/properties/cue_before.c",
    "src/select/properties/cursor.c",
    "src/select/properties/direction.c",
    "src/select/properties/display.c",
    "src/select/properties/elevation.c",
    "src/select/properties/empty_cells.c",
    "src/select/properties/fill_opacity.c",
    "src/select/properties/flex_basis.c",
    "src/select/properties/flex_direction.c",
    "src/select/properties/flex_grow.c",
    "src/select/properties/flex_shrink.c",
    "src/select/properties/flex_wrap.c",
    "src/select/properties/float.c",
    "src/select/properties/font_family.c",
    "src/select/properties/font_size.c",
    "src/select/properties/font_style.c",
    "src/select/properties/font_variant.c",
    "src/select/properties/font_weight.c",
    "src/select/properties/height.c",
    "src/select/properties/helpers.c",
    "src/select/properties/justify_content.c",
    "src/select/properties/left.c",
    "src/select/properties/letter_spacing.c",
    "src/select/properties/line_height.c",
    "src/select/properties/list_style_image.c",
    "src/select/properties/list_style_position.c",
    "src/select/properties/list_style_type.c",
    "src/select/properties/margin_bottom.c",
    "src/select/properties/margin_left.c",
    "src/select/properties/margin_right.c",
    "src/select/properties/margin_top.c",
    "src/select/properties/max_height.c",
    "src/select/properties/max_width.c",
    "src/select/properties/min_height.c",
    "src/select/properties/min_width.c",
    "src/select/properties/opacity.c",
    "src/select/properties/order.c",
    "src/select/properties/orphans.c",
    "src/select/properties/outline_color.c",
    "src/select/properties/outline_style.c",
    "src/select/properties/outline_width.c",
    "src/select/properties/overflow_x.c",
    "src/select/properties/overflow_y.c",
    "src/select/properties/padding_bottom.c",
    "src/select/properties/padding_left.c",
    "src/select/properties/padding_right.c",
    "src/select/properties/padding_top.c",
    "src/select/properties/page_break_after.c",
    "src/select/properties/page_break_before.c",
    "src/select/properties/page_break_inside.c",
    "src/select/properties/pause_after.c",
    "src/select/properties/pause_before.c",
    "src/select/properties/pitch.c",
    "src/select/properties/pitch_range.c",
    "src/select/properties/play_during.c",
    "src/select/properties/position.c",
    "src/select/properties/quotes.c",
    "src/select/properties/richness.c",
    "src/select/properties/right.c",
    "src/select/properties/speak.c",
    "src/select/properties/speak_header.c",
    "src/select/properties/speak_numeral.c",
    "src/select/properties/speak_punctuation.c",
    "src/select/properties/speech_rate.c",
    "src/select/properties/stress.c",
    "src/select/properties/stroke_opacity.c",
    "src/select/properties/table_layout.c",
    "src/select/properties/text_align.c",
    "src/select/properties/text_decoration.c",
    "src/select/properties/text_indent.c",
    "src/select/properties/text_transform.c",
    "src/select/properties/top.c",
    "src/select/properties/unicode_bidi.c",
    "src/select/properties/vertical_align.c",
    "src/select/properties/visibility.c",
    "src/select/properties/voice_family.c",
    "src/select/properties/volume.c",
    "src/select/properties/white_space.c",
    "src/select/properties/widows.c",
    "src/select/properties/width.c",
    "src/select/properties/word_spacing.c",
    "src/select/properties/writing_mode.c",
    "src/select/properties/z_index.c",
    "src/select/select.c",
    "src/select/strings.c",
    "src/select/unit.c",
    "src/stylesheet.c",
    "src/utils/errors.c",
    "src/utils/utils.c",
};
