FROM archlinux:latest

# Use multiple mirrors and increase timeout
RUN echo 'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch' > /etc/pacman.d/mirrorlist && \
    echo 'Server = https://ftp.jaist.ac.jp/pub/Linux/ArchLinux/$repo/os/$arch' >> /etc/pacman.d/mirrorlist && \
    echo 'Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch' >> /etc/pacman.d/mirrorlist && \
    sed -i 's/^#DisableDownloadTimeout/DisableDownloadTimeout/' /etc/pacman.conf || true

# Install X11 libs first (small packages), then firefox separately
RUN pacman -Syu --noconfirm --disable-download-timeout && \
    pacman -S --noconfirm --disable-download-timeout \
    xorg-server-xvfb \
    xorg-xdpyinfo \
    xorg-xwd \
    imagemagick \
    ttf-dejavu \
    libxcb \
    xcb-util \
    xcb-util-image \
    xcb-util-keysyms \
    xcb-util-wm \
    libx11 \
    curl \
    sqlite \
    libssh2 \
    woff2 \
    libwebp \
    brotli \
    fontconfig

RUN pacman -S --noconfirm --disable-download-timeout firefox \
    && pacman -Scc --noconfirm

WORKDIR /app

# Copy the built suzume binary and test script
COPY zig-out/bin/suzume /app/suzume
COPY tests/compare-firefox.sh /app/compare-firefox.sh
COPY tests/error-check.sh /app/error-check.sh
RUN chmod +x /app/suzume /app/compare-firefox.sh /app/error-check.sh

# Create output directory
RUN mkdir -p /app/results/suzume /app/results/firefox /app/results/diff

ENTRYPOINT ["/app/compare-firefox.sh"]
