#!/usr/bin/env python3
"""Generate IDNA mapping + NFC tables for src/url/tables.zig.

Reads:
  tools/IdnaMappingTable.txt    (UTS #46, Unicode 16.0)
  tools/UnicodeData.txt         (NFC decomposition + CCC)
  tools/CompositionExclusions.txt

Writes:
  src/url/tables.zig

Usage:
  python3 tools/gen_idna_tables.py
"""

import os
import sys
from pathlib import Path

TOOLS = Path(__file__).parent
OUT = TOOLS.parent / "src" / "url" / "tables.zig"


# ── IDNA Mapping Table ────────────────────────────────────────────────

def parse_idna_table(path):
    """Parse IdnaMappingTable.txt → list of (range_start, range_end, status, mapping)."""
    entries = []
    for line in open(path):
        line = line.split("#")[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        cp_range = parts[0]
        status = parts[1]

        # Parse code point range
        if ".." in cp_range:
            start_s, end_s = cp_range.split("..")
            start, end = int(start_s, 16), int(end_s, 16)
        else:
            start = end = int(cp_range, 16)

        # Parse mapping (if present)
        mapping = None
        if len(parts) >= 3 and parts[2]:
            mapping = [int(cp, 16) for cp in parts[2].split()]

        entries.append((start, end, status, mapping))

    return entries


STATUS_MAP = {
    "valid": "valid",
    "ignored": "ignored",
    "mapped": "mapped",
    "deviation": "deviation",
    "disallowed": "disallowed",
    "disallowed_STD3_valid": "disallowed_STD3_valid",
    "disallowed_STD3_mapped": "disallowed_STD3_mapped",
}


# ── NFC Tables ────────────────────────────────────────────────────────

def parse_unicode_data(path):
    """Parse UnicodeData.txt → (decompositions, ccc_map).

    decompositions: dict of cp → [cp, ...] (canonical only, no <compat> tags)
    ccc_map: dict of cp → int (Canonical_Combining_Class, only non-zero)
    """
    decompositions = {}
    ccc_map = {}

    for line in open(path):
        fields = line.strip().split(";")
        if len(fields) < 15:
            continue
        cp = int(fields[0], 16)
        ccc = int(fields[3])
        decomp = fields[5].strip()

        if ccc != 0:
            ccc_map[cp] = ccc

        # Only canonical decomposition (no compatibility tag like <compat>)
        if decomp and not decomp.startswith("<"):
            mapping = [int(x, 16) for x in decomp.split()]
            decompositions[cp] = mapping

    return decompositions, ccc_map


def parse_composition_exclusions(path):
    """Parse CompositionExclusions.txt → set of excluded code points."""
    exclusions = set()
    for line in open(path):
        line = line.split("#")[0].strip()
        if not line:
            continue
        cp = int(line.split()[0], 16)
        exclusions.add(cp)
    return exclusions


def build_composition_pairs(decompositions, exclusions):
    """Build canonical composition pairs: (starter, combining) → composed.

    A pair is composable if:
    - The decomposition is canonical (length 2)
    - The first character has CCC=0 (is a starter)
    - The composed character is not in CompositionExclusions
    - The composed character is not a Hangul syllable (handled algorithmically)
    """
    pairs = {}
    for composed, decomp in decompositions.items():
        if len(decomp) != 2:
            continue
        if composed in exclusions:
            continue
        # Skip Hangul (handled algorithmically: U+AC00..U+D7A3)
        if 0xAC00 <= composed <= 0xD7A3:
            continue
        first, second = decomp
        pairs[(first, second)] = composed
    return pairs


# ── Zig Code Generation ──────────────────────────────────────────────

def gen_zig(idna_entries, decompositions, ccc_map, composition_pairs):
    lines = []
    lines.append("// Auto-generated by tools/gen_idna_tables.py — DO NOT EDIT")
    lines.append("// Unicode 16.0, UTS #46")
    lines.append("")
    lines.append("const std = @import(\"std\");")
    lines.append("")

    # ── IDNA Status enum ──
    lines.append("pub const Status = enum {")
    lines.append("    valid,")
    lines.append("    ignored,")
    lines.append("    mapped,")
    lines.append("    deviation,")
    lines.append("    disallowed,")
    lines.append("    disallowed_STD3_valid,")
    lines.append("    disallowed_STD3_mapped,")
    lines.append("};")
    lines.append("")

    # ── Mapping data pool (flat array of u21) ──
    # Collect all unique mappings and store them in a flat pool.
    # Each IdnaEntry references a slice into this pool via offset+length.
    mapping_pool = []
    mapping_offsets = {}  # tuple(mapping) → (offset, length)

    for start, end, status, mapping in idna_entries:
        if mapping is not None:
            key = tuple(mapping)
            if key not in mapping_offsets:
                offset = len(mapping_pool)
                mapping_pool.extend(mapping)
                mapping_offsets[key] = (offset, len(mapping))

    lines.append("/// Flat pool of mapping code points. IdnaEntry references slices into this.")
    lines.append(f"pub const mapping_pool = [_]u21{{")
    for i in range(0, len(mapping_pool), 16):
        chunk = mapping_pool[i:i+16]
        vals = ", ".join(f"0x{cp:04X}" for cp in chunk)
        lines.append(f"    {vals},")
    lines.append("};")
    lines.append("")

    # ── IdnaEntry struct ──
    lines.append("pub const IdnaEntry = struct {")
    lines.append("    range_start: u21,")
    lines.append("    range_end: u21,")
    lines.append("    status: Status,")
    lines.append("    mapping_offset: u16,  // into mapping_pool")
    lines.append("    mapping_len: u8,")
    lines.append("};")
    lines.append("")

    # ── IDNA table ──
    lines.append(f"/// IDNA mapping table ({len(idna_entries)} entries). Sorted by range_start.")
    lines.append(f"pub const idna_table = [_]IdnaEntry{{")
    for start, end, status, mapping in idna_entries:
        s = STATUS_MAP.get(status, "disallowed")
        if mapping is not None:
            key = tuple(mapping)
            off, length = mapping_offsets[key]
            lines.append(f"    .{{ .range_start = 0x{start:04X}, .range_end = 0x{end:04X}, .status = .{s}, .mapping_offset = {off}, .mapping_len = {length} }},")
        else:
            lines.append(f"    .{{ .range_start = 0x{start:04X}, .range_end = 0x{end:04X}, .status = .{s}, .mapping_offset = 0, .mapping_len = 0 }},")
    lines.append("};")
    lines.append("")

    # ── lookupCodePoint ──
    lines.append("/// Binary search for a code point in the IDNA table.")
    lines.append("pub fn lookupCodePoint(cp: u21) IdnaEntry {")
    lines.append("    var lo: usize = 0;")
    lines.append("    var hi: usize = idna_table.len;")
    lines.append("    while (lo < hi) {")
    lines.append("        const mid = lo + (hi - lo) / 2;")
    lines.append("        if (idna_table[mid].range_end < cp) {")
    lines.append("            lo = mid + 1;")
    lines.append("        } else if (idna_table[mid].range_start > cp) {")
    lines.append("            hi = mid;")
    lines.append("        } else {")
    lines.append("            return idna_table[mid];")
    lines.append("        }")
    lines.append("    }")
    lines.append("    // Not found — treat as disallowed")
    lines.append("    return .{ .range_start = cp, .range_end = cp, .status = .disallowed, .mapping_offset = 0, .mapping_len = 0 };")
    lines.append("}")
    lines.append("")

    lines.append("/// Get the mapping slice for an entry from the pool.")
    lines.append("pub fn getMapping(entry: IdnaEntry) []const u21 {")
    lines.append("    if (entry.mapping_len == 0) return &.{};")
    lines.append("    return mapping_pool[entry.mapping_offset..][0..entry.mapping_len];")
    lines.append("}")
    lines.append("")

    # ── NFC Canonical Decomposition ──
    # Store as sorted array of (cp, decomp_offset, decomp_len) + flat pool
    decomp_pool = []
    decomp_entries = []  # (cp, offset, length)

    for cp in sorted(decompositions.keys()):
        mapping = decompositions[cp]
        offset = len(decomp_pool)
        decomp_pool.extend(mapping)
        decomp_entries.append((cp, offset, len(mapping)))

    lines.append("// ── NFC Tables ─────────────────────────────────────────────────────")
    lines.append("")
    lines.append(f"/// Canonical decomposition pool ({len(decomp_pool)} code points).")
    lines.append("pub const decomp_pool = [_]u21{")
    for i in range(0, len(decomp_pool), 16):
        chunk = decomp_pool[i:i+16]
        vals = ", ".join(f"0x{cp:04X}" for cp in chunk)
        lines.append(f"    {vals},")
    lines.append("};")
    lines.append("")

    lines.append("pub const DecompEntry = struct { cp: u21, offset: u16, len: u8 };")
    lines.append("")
    lines.append(f"/// Canonical decomposition entries ({len(decomp_entries)} entries). Sorted by cp.")
    lines.append("pub const decomp_table = [_]DecompEntry{")
    for cp, offset, length in decomp_entries:
        lines.append(f"    .{{ .cp = 0x{cp:04X}, .offset = {offset}, .len = {length} }},")
    lines.append("};")
    lines.append("")

    lines.append("/// Binary search for canonical decomposition of a code point.")
    lines.append("pub fn getDecomposition(cp: u21) ?[]const u21 {")
    lines.append("    var lo: usize = 0;")
    lines.append("    var hi: usize = decomp_table.len;")
    lines.append("    while (lo < hi) {")
    lines.append("        const mid = lo + (hi - lo) / 2;")
    lines.append("        if (decomp_table[mid].cp < cp) {")
    lines.append("            lo = mid + 1;")
    lines.append("        } else if (decomp_table[mid].cp > cp) {")
    lines.append("            hi = mid;")
    lines.append("        } else {")
    lines.append("            const e = decomp_table[mid];")
    lines.append("            return decomp_pool[e.offset..][0..e.len];")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return null;")
    lines.append("}")
    lines.append("")

    # ── CCC (Canonical Combining Class) ──
    # Store as sorted array of (cp, ccc)
    ccc_entries = sorted(ccc_map.items())

    lines.append(f"/// Canonical Combining Class entries ({len(ccc_entries)} entries). Sorted by cp.")
    lines.append("pub const CccEntry = struct { cp: u21, ccc: u8 };")
    lines.append("pub const ccc_table = [_]CccEntry{")
    for cp, ccc in ccc_entries:
        lines.append(f"    .{{ .cp = 0x{cp:04X}, .ccc = {ccc} }},")
    lines.append("};")
    lines.append("")

    lines.append("/// Get Canonical Combining Class for a code point (0 if not found).")
    lines.append("pub fn getCcc(cp: u21) u8 {")
    lines.append("    var lo: usize = 0;")
    lines.append("    var hi: usize = ccc_table.len;")
    lines.append("    while (lo < hi) {")
    lines.append("        const mid = lo + (hi - lo) / 2;")
    lines.append("        if (ccc_table[mid].cp < cp) {")
    lines.append("            lo = mid + 1;")
    lines.append("        } else if (ccc_table[mid].cp > cp) {")
    lines.append("            hi = mid;")
    lines.append("        } else {")
    lines.append("            return ccc_table[mid].ccc;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")

    # ── Composition Pairs ──
    # Store as sorted array of (first, second, composed)
    comp_entries = sorted(composition_pairs.items())

    lines.append(f"/// Canonical composition pairs ({len(comp_entries)} pairs). Sorted by (first, second).")
    lines.append("pub const CompPair = struct { first: u21, second: u21, composed: u21 };")
    lines.append("pub const comp_table = [_]CompPair{")
    for (first, second), composed in comp_entries:
        lines.append(f"    .{{ .first = 0x{first:04X}, .second = 0x{second:04X}, .composed = 0x{composed:04X} }},")
    lines.append("};")
    lines.append("")

    lines.append("/// Look up a canonical composition pair.")
    lines.append("pub fn getComposition(first: u21, second: u21) ?u21 {")
    lines.append("    var lo: usize = 0;")
    lines.append("    var hi: usize = comp_table.len;")
    lines.append("    while (lo < hi) {")
    lines.append("        const mid = lo + (hi - lo) / 2;")
    lines.append("        const e = comp_table[mid];")
    lines.append("        if (e.first < first or (e.first == first and e.second < second)) {")
    lines.append("            lo = mid + 1;")
    lines.append("        } else if (e.first > first or (e.first == first and e.second > second)) {")
    lines.append("            hi = mid;")
    lines.append("        } else {")
    lines.append("            return e.composed;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return null;")
    lines.append("}")
    lines.append("")

    # ── Tests ──
    lines.append("// ── Tests ─────────────────────────────────────────────────────────")
    lines.append("")
    lines.append('test "lookupCodePoint ASCII lowercase is valid" {')
    lines.append("    const entry = lookupCodePoint('a');")
    lines.append("    try std.testing.expect(entry.status == .valid);")
    lines.append("}")
    lines.append("")
    lines.append('test "lookupCodePoint ASCII uppercase is mapped" {')
    lines.append("    const entry = lookupCodePoint('A');")
    lines.append("    try std.testing.expect(entry.status == .mapped);")
    lines.append("    const m = getMapping(entry);")
    lines.append("    try std.testing.expectEqual(@as(u21, 'a'), m[0]);")
    lines.append("}")
    lines.append("")
    lines.append('test "lookupCodePoint fullwidth maps" {')
    lines.append("    // U+FF21 FULLWIDTH LATIN CAPITAL LETTER A")
    lines.append("    const entry = lookupCodePoint(0xFF21);")
    lines.append("    try std.testing.expect(entry.status == .mapped);")
    lines.append("}")
    lines.append("")
    lines.append('test "lookupCodePoint U+0080 control is disallowed" {')
    lines.append("    const entry = lookupCodePoint(0x0080);")
    lines.append("    try std.testing.expect(entry.status == .disallowed);")
    lines.append("}")
    lines.append("")
    lines.append('test "getCcc for combining acute accent" {')
    lines.append("    // U+0301 COMBINING ACUTE ACCENT has CCC=230")
    lines.append("    try std.testing.expectEqual(@as(u8, 230), getCcc(0x0301));")
    lines.append("}")
    lines.append("")
    lines.append('test "getCcc for base character is 0" {')
    lines.append("    try std.testing.expectEqual(@as(u8, 0), getCcc('a'));")
    lines.append("}")
    lines.append("")
    lines.append('test "getDecomposition e-acute" {')
    lines.append("    // U+00E9 LATIN SMALL LETTER E WITH ACUTE → U+0065 U+0301")
    lines.append("    const d = getDecomposition(0x00E9).?;")
    lines.append("    try std.testing.expectEqual(@as(usize, 2), d.len);")
    lines.append("    try std.testing.expectEqual(@as(u21, 0x0065), d[0]);")
    lines.append("    try std.testing.expectEqual(@as(u21, 0x0301), d[1]);")
    lines.append("}")
    lines.append("")
    lines.append('test "getDecomposition ASCII returns null" {')
    lines.append("    try std.testing.expect(getDecomposition('a') == null);")
    lines.append("}")
    lines.append("")
    lines.append('test "getComposition e + acute" {')
    lines.append("    // U+0065 + U+0301 → U+00E9")
    lines.append("    const c = getComposition(0x0065, 0x0301).?;")
    lines.append("    try std.testing.expectEqual(@as(u21, 0x00E9), c);")
    lines.append("}")
    lines.append("")
    lines.append('test "getComposition nonexistent pair" {')
    lines.append("    try std.testing.expect(getComposition('a', 'b') == null);")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    idna_path = TOOLS / "IdnaMappingTable.txt"
    udata_path = TOOLS / "UnicodeData.txt"
    excl_path = TOOLS / "CompositionExclusions.txt"

    for p in [idna_path, udata_path, excl_path]:
        if not p.exists():
            print(f"ERROR: {p} not found. Download Unicode data files first.", file=sys.stderr)
            sys.exit(1)

    print("Parsing IDNA mapping table...", file=sys.stderr)
    idna_entries = parse_idna_table(idna_path)
    print(f"  {len(idna_entries)} entries", file=sys.stderr)

    print("Parsing UnicodeData.txt...", file=sys.stderr)
    decompositions, ccc_map = parse_unicode_data(udata_path)
    print(f"  {len(decompositions)} decompositions, {len(ccc_map)} CCC entries", file=sys.stderr)

    print("Parsing CompositionExclusions.txt...", file=sys.stderr)
    exclusions = parse_composition_exclusions(excl_path)
    print(f"  {len(exclusions)} exclusions", file=sys.stderr)

    print("Building composition pairs...", file=sys.stderr)
    comp_pairs = build_composition_pairs(decompositions, exclusions)
    print(f"  {len(comp_pairs)} composition pairs", file=sys.stderr)

    print("Generating Zig code...", file=sys.stderr)
    code = gen_zig(idna_entries, decompositions, ccc_map, comp_pairs)

    OUT.write_text(code)
    size_kb = len(code) / 1024
    print(f"Written {OUT} ({size_kb:.0f} KB)", file=sys.stderr)


if __name__ == "__main__":
    main()
