#!/usr/bin/env python3
"""Generate src/url/bidi_class.zig from UnicodeData.txt (field 4 = Bidi_Class).

Usage: python3 tools/gen_bidi_class.py path/to/UnicodeData.txt > src/url/bidi_class.zig

Only the classes RFC 5893 (IDNA Bidi Rule) distinguishes are kept; everything
else (L, and classes irrelevant to the rule like LRE/PDF/WS/S/B) collapses to
.l_or_other, which the rule treats identically to L for membership tests.
Default ranges for unassigned code points follow DerivedBidiClass.txt
@missing lines (R/AL/ET blocks), emitted as trailing low-priority ranges.
"""
import sys

KEEP = {"R":"r","AL":"al","AN":"an","EN":"en","ES":"es","CS":"cs","ET":"et",
        "ON":"on","BN":"bn","NSM":"nsm"}

def main():
    entries = []  # (start, end, class)
    prev_first = None
    with open(sys.argv[1]) as f:
        rows = []
        for line in f:
            parts = line.split(";")
            cp = int(parts[0], 16); name = parts[1]; bc = parts[4]
            rows.append((cp, name, bc))
    i = 0
    while i < len(rows):
        cp, name, bc = rows[i]
        if name.endswith(", First>"):
            last_cp = rows[i+1][0]
            i += 2
            if bc in KEEP: entries.append((cp, last_cp, KEEP[bc]))
            continue
        i += 1
        if bc in KEEP: entries.append((cp, cp, KEEP[bc]))
    # merge adjacent
    merged = []
    for s, e, c in sorted(entries):
        if merged and merged[-1][2] == c and merged[-1][1] + 1 == s:
            merged[-1][1] = e
        else:
            merged.append([s, e, c])
    # DerivedBidiClass.txt @missing defaults (unassigned code points):
    defaults = [
        (0x0590,0x05FF,"r"),(0x07C0,0x085F,"al"),(0x0860,0x08FF,"al"),
        (0x0600,0x07BF,"al"),(0xFB1D,0xFB4F,"r"),(0xFB50,0xFDCF,"al"),
        (0xFDF0,0xFDFF,"al"),(0xFE70,0xFEFF,"al"),(0x10800,0x10CFF,"r"),
        (0x10D00,0x10D3F,"al"),(0x10EC0,0x10EFF,"al"),(0x10F00,0x10F2F,"r"),
        (0x10F30,0x10F6F,"al"),(0x10F70,0x10FFF,"r"),(0x1E800,0x1EC6F,"r"),
        (0x1EC70,0x1ECBF,"al"),(0x1ECC0,0x1ECFF,"al"),(0x1ED00,0x1ED4F,"al"),
        (0x1ED50,0x1EDFF,"al"),(0x1EE00,0x1EEFF,"al"),(0x1EF00,0x1EFFF,"r"),
        (0x20A0,0x20CF,"et"),
    ]
    print("//! GENERATED by tools/gen_bidi_class.py from UnicodeData.txt 17.0.0 —")
    print("//! do not hand-edit; regenerate instead. Bidi_Class subset for the")
    print("//! RFC 5893 Bidi Rule (IDNA CheckBidi). Unlisted code points are")
    print("//! .l_or_other unless covered by the trailing unassigned-defaults scan.")
    print("""
pub const BidiClass = enum { l_or_other, r, al, an, en, es, cs, et, on, bn, nsm };

const Range = struct { start: u21, end: u21, class: BidiClass };
""")
    print("const ranges = [_]Range{")
    for s, e, c in merged:
        print(f"    .{{ .start = 0x{s:04X}, .end = 0x{e:04X}, .class = .{c} }},")
    print("};")
    print("""
// Default Bidi_Class ranges for *unassigned* code points (DerivedBidiClass
// @missing). Checked only when the code point is not in `ranges`.
const unassigned_defaults = [_]Range{""")
    for s, e, c in defaults:
        print(f"    .{{ .start = 0x{s:04X}, .end = 0x{e:04X}, .class = .{c} }},")
    print("""};

pub fn bidiClass(cp: u21) BidiClass {
    var lo: usize = 0;
    var hi: usize = ranges.len;
    while (lo < hi) {
        const mid = (lo + hi) / 2;
        const r = ranges[mid];
        if (cp < r.start) {
            hi = mid;
        } else if (cp > r.end) {
            lo = mid + 1;
        } else {
            return r.class;
        }
    }
    for (unassigned_defaults) |r| {
        if (cp >= r.start and cp <= r.end) return r.class;
    }
    return .l_or_other;
}""")

main()
