#!/usr/bin/env python3
"""Generate src/url/combining_mark.zig from UnicodeData.txt (field 2 = General_Category).

Usage: python3 tools/gen_combining_mark.py tools/UnicodeData.txt > src/url/combining_mark.zig

Emits sorted ranges of code points with General_Category Mn or Me, used by
UTS #46 §4.2 step 2 (label must not begin with a combining mark).
"""
import sys

def main():
    cps = []
    with open(sys.argv[1]) as f:
        rows = []
        for line in f:
            parts = line.split(";")
            rows.append((int(parts[0], 16), parts[1], parts[2]))
    i = 0
    while i < len(rows):
        cp, name, gc = rows[i]
        if name.endswith(", First>"):
            last = rows[i + 1][0]
            if gc in ("Mn", "Me"):
                cps.extend(range(cp, last + 1))
            i += 2
            continue
        if gc in ("Mn", "Me"):
            cps.append(cp)
        i += 1
    # collapse to ranges
    ranges = []
    for cp in cps:
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    print("//! GENERATED by tools/gen_combining_mark.py — do not edit by hand.")
    print("//! General_Category Mn/Me ranges from UnicodeData.txt.")
    print()
    print("const ranges = [_][2]u21{")
    for a, b in ranges:
        print(f"    .{{ 0x{a:04X}, 0x{b:04X} }},")
    print("};")
    print("""
/// True if cp has General_Category Mn or Me (combining mark).
pub fn isCombiningMark(cp: u21) bool {
    var lo: usize = 0;
    var hi: usize = ranges.len;
    while (lo < hi) {
        const mid = (lo + hi) / 2;
        if (cp < ranges[mid][0]) {
            hi = mid;
        } else if (cp > ranges[mid][1]) {
            lo = mid + 1;
        } else {
            return true;
        }
    }
    return false;
}""")

if __name__ == "__main__":
    main()
